[tool.ruff]
target-version = "py312"  # 要定位的最低 Python 版本
line-length = 119         # 强制执行长行违规时使用的行长度
indent-width = 4          # 每个缩进级别（制表符）的空格数

[tool.ruff.lint]
# 要忽略的规则代码或前缀的列表
ignore = []  # "I001", "E701", "W293"
select = [                        # 要启用的规则代码或 prefix 列表
    "F", "E", "W", "I",
    "N", "PERF", "RUF"
]

[tool.ruff.lint.isort]
# 在导入后放置的空行数
lines-after-imports = 2

[tool.ruff.format]
docstring-code-format = true      # 是否格式化文档字符串中的代码片段
skip-magic-trailing-comma = true  # Ruff 使用现有的尾随逗号作为短行应保持分开的指示
